### ISSUE TITLE
Adding Aiohttp plugin

### ISSUE THREAD

**Issue by dandreevv** [marshmallow-code/apispec-webframeworks#100]
I want to add a plugin for the [aiohttp](https://docs.aiohttp.org/en/stable/) framework. Are you interested in it?

**Comment by andreaturli** [comment]
Happy to help with the testing of it!

**Comment by S4mw1s3** [comment]
If you are still interested, I just made an attempt: https://github.com/marshmallow-code/apispec-webframeworks/pull/136

**Comment by sloria** [comment]
closed by #136
