### ISSUE TITLE
Feature Request: Skipping endpoints

### ISSUE THREAD

**Issue by claweyenuk** [marshmallow-code/apispec-webframeworks#101]
I have a project with some endpoints that are just for the local DEV environments where nginx is not running.

I would like to skip them when generating swagger docs. I do not see such a feature, is this something that would be considered useful?

Is there any suggested way to implement this? I was thinking that a decorator would make the most sense, something like @apispec_skip_docs. Any suggestions?

**Comment by lafrech** [comment]
I may be missing something but why do you pass those endpoints to apispec (by calling `spec.path`) in the first place?
