### ISSUE TITLE
Failed to integrate apispec-webframeworks-0.4.0 with apispec-3.0.0

### ISSUE THREAD

**Issue by iwansyahp** [marshmallow-code/apispec-webframeworks#59]
I used this cookiecutter-based Flask project with no explicit apispec an apispec-webframework specified. I got this error when installing dependencies via requirements.txt file.

![image](https://user-images.githubusercontent.com/2720357/65217487-60044c00-dade-11e9-8371-d6b8fb82f3de.png)

My temporary solution is to use apispec v.2.0.2 with apispec-webframeworks v.0.4.0.

**Comment by lafrech** [comment]
This is fixed in dev branch but not released yet.

**Comment by whoiswes** [comment]
@lafrech, do we have an ETA on release?

**Comment by sloria** [comment]
I'll cut a release.

**Comment by sloria** [comment]
0.5.0 released

**Comment by whoiswes** [comment]
You guys are awesome!
